server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: spring-boot-admin-server
  boot:
    admin:
      client:
        url: http://localhost:8888

# http://localhost:8080/actuator/jolokia/read/org.springframework.boot:name=metricsEndpoint,type=Endpoint/Data